# -*- coding: utf-8 -*-
"""quantumvisualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MM6ksd-qzpq1tZCECHDDm1K6O5boYEUG
"""

!pip install qiskit
!pip install qiskit-aer

from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit import transpile
import matplotlib.pyplot as plt

qc = QuantumCircuit(2, 2)

qc.h(0)
qc.h(1)

qc.measure([0,1], [0,1])

sim = Aer.get_backend('aer_simulator')

compiled_circuit = transpile(qc, sim)
result = sim.run(compiled_circuit, shots=1000).result()

counts = result.get_counts()

plt.bar(counts.keys(), counts.values())
plt.xlabel("States")
plt.ylabel("Counts")
plt.title("Quantum State Distribution")

plt.show()